import { test, expect } from './fixture'

// A 500,049-unit repeated Korean/emoji thought took about 59 s of layout in
// one inline paragraph in desktop Chromium. The bounds below only catch a
// return of that stall; they are not a frame-rate benchmark.
const completionBoundMs = 20_000
const frameGapBoundMs = 2_000

test.use({ viewport: { width: 393, height: 760 }, deviceScaleFactor: 2.75, isMobile: true, hasTouch: true })

for (const kind of ['repeated', 'ascii'] as const) {
    test(`expanding a large ${kind} thought reaches the exact end without a long stall`, async ({ page }) => {
        await page.goto('/')
        const sizes = await page.evaluate((kind) => window.thought.mount(kind), kind)
        expect(sizes.sourceLength).toBeGreaterThanOrEqual(500_000)
        const started = await page.evaluate(() => window.thought.toggle())
        await page.waitForFunction(() => window.thought.state.complete, undefined, { timeout: completionBoundMs, polling: 100 })
        const finished = await page.evaluate(() => performance.now())
        const state = await page.evaluate(() => window.thought.state)
        test.info().annotations.push({ type: 'timing', description: JSON.stringify({ kind, completeMs: Math.round(finished - started), maxFrameGapMs: Math.round(state.maxFrameGap), units: state.units }) })
        expect(state.open).toBe(true)
        expect(state.length).toBe(sizes.expectedLength)
        expect(state.endsWithLatest).toBe(true)
        expect(state.units).toBeGreaterThan(200)
        expect(state.maxFrameGap).toBeLessThan(frameGapBoundMs)
    })
}

test('collapsing during the incremental expansion is handled promptly and stops the work', async ({ page }) => {
    await page.goto('/')
    await page.evaluate(() => window.thought.mount('repeated'))
    await page.evaluate(() => window.thought.toggle())
    await page.evaluate(() => window.thought.frames(2))
    const partial = await page.evaluate(() => window.thought.state)
    expect(partial.open).toBe(true)
    expect(partial.complete).toBe(false)
    const clicked = await page.evaluate(() => window.thought.toggle())
    await page.evaluate(() => window.thought.frames(10))
    const collapsed = await page.evaluate(() => window.thought.state)
    expect(collapsed.open).toBe(false)
    expect(collapsed.units).toBe(0)
    const closing = collapsed.toggles.find((toggle) => !toggle.open)
    expect(closing).toBeDefined()
    expect(closing!.at - clicked).toBeLessThan(frameGapBoundMs)
    expect(collapsed.maxFrameGap).toBeLessThan(frameGapBoundMs)
})

for (const shape of ['no-newline', 'periodic-break', 'paragraph'] as const) {
    test(`settled ${shape} thought preserves parser output and expands without a long stall`, async ({ page }) => {
        // Allow the renderer to return diagnostic evidence even if the acceptance bound fails.
        test.setTimeout(120_000)
        await page.goto('/settledThought.html')
        const sizes = await page.evaluate(shape => window.settledThought.mount(shape), shape)
        expect(sizes.sourceLength).toBeGreaterThanOrEqual(500_000)
        expect(sizes.sourceContentPreserved).toBe(true)
        await page.waitForFunction(() => window.settledThought.state.settled || window.settledThought.state.error)
        await page.evaluate(() => window.settledThought.frames(3))
        const before = await page.evaluate(() => window.settledThought.state)
        expect(before.error).toBe(false)
        expect(before.open).toBe(false)
        await page.evaluate(() => window.settledThought.resetTiming())
        const started = await page.evaluate(() => window.settledThought.toggle())
        await page.waitForFunction(() => window.settledThought.state.exactText, undefined, { polling: 100 })
        await page.evaluate(() => window.settledThought.frames(3))
        const finished = await page.evaluate(() => performance.now())
        const state = await page.evaluate(() => window.settledThought.state)
        const timing = { shape, parseMs: sizes.parseMs, toggleHandlerMs: state.toggleHandlerMs, expandMs: finished - started, maxFrameGapMs: state.maxFrameGap, elementCount: state.elementCount }
        test.info().annotations.push({ type: 'settled-thought-timing', description: JSON.stringify(timing) })
        await test.info().attach('settled-thought-timing', { body: JSON.stringify(timing), contentType: 'application/json' })
        expect(state.open).toBe(true)
        expect(state.exactText).toBe(true)
        expect(state.exactMarkup).toBe(true)
        expect(state.length).toBe(sizes.expectedLength)
        expect(state.endsWithLatest).toBe(true)
        expect(state.thoughtBold).toBe('SYNTHETIC-BOLD')
        expect(state.thoughtLink).toBe('https://example.invalid/synthetic')
        expect(state.answerBold).toBe(true)
        expect(state.answerLink).toBe(true)
        const collapsedAt = await page.evaluate(() => window.settledThought.toggle())
        await page.evaluate(() => window.settledThought.frames(3))
        expect((await page.evaluate(() => window.settledThought.state)).open).toBe(false)
        expect(await page.evaluate(() => performance.now()) - collapsedAt).toBeLessThan(frameGapBoundMs)
        expect(finished - started).toBeLessThan(completionBoundMs)
        expect(state.maxFrameGap).toBeLessThan(frameGapBoundMs)
    })
}

test('expanded preview settles collapsed when its text needs bounded expansion', async ({ page }) => {
    test.setTimeout(120_000)
    await page.goto('/settledThought.html')
    await page.evaluate(() => window.settledThought.mount('no-newline', true))
    await page.evaluate(() => window.settledThought.toggle())
    await page.waitForFunction(() => window.settledThought.state.previewOpen)
    const started = await page.evaluate(() => window.settledThought.settle())
    await page.waitForFunction(() => window.settledThought.state.settled || window.settledThought.state.error)
    await page.evaluate(() => window.settledThought.frames(3))
    const state = await page.evaluate(() => window.settledThought.state)
    const timing = { transitionMs: state.readyAt - started, maxFrameGapMs: state.maxFrameGap }
    test.info().annotations.push({ type: 'settled-thought-transition', description: JSON.stringify(timing) })
    await test.info().attach('settled-thought-transition', { body: JSON.stringify(timing), contentType: 'application/json' })
    expect(state.error).toBe(false)
    expect(state.hasPreview).toBe(false)
    expect(state.open).toBe(false)
    expect(state.units).toBe(0)
    expect(state.answerBold).toBe(true)
    expect(state.answerLink).toBe(true)
    expect(state.readyAt - started).toBeLessThan(completionBoundMs)
    expect(state.maxFrameGap).toBeLessThan(frameGapBoundMs)
    await page.evaluate(() => window.settledThought.resetTiming())
    const expandedAt = await page.evaluate(() => window.settledThought.toggle())
    await page.waitForFunction(() => window.settledThought.state.exactText, undefined, { polling: 100 })
    await page.evaluate(() => window.settledThought.frames(3))
    const expanded = await page.evaluate(() => window.settledThought.state)
    expect(expanded.exactMarkup).toBe(true)
    expect(expanded.maxFrameGap).toBeLessThan(frameGapBoundMs)
    expect(await page.evaluate(() => performance.now()) - expandedAt).toBeLessThan(completionBoundMs)
})

test('settled expansion cancels on collapse and reopens with exact content', async ({ page }) => {
    await page.goto('/settledThought.html')
    await page.evaluate(() => window.settledThought.mount('no-newline'))
    await page.waitForFunction(() => window.settledThought.state.settled)
    await page.evaluate(() => window.settledThought.toggle())
    await page.evaluate(() => window.settledThought.frames(2))
    const partial = await page.evaluate(() => window.settledThought.state)
    expect(partial.open).toBe(true)
    expect(partial.exactText).toBe(false)
    expect(partial.units).toBeGreaterThan(0)
    const clicked = await page.evaluate(() => window.settledThought.toggle())
    await page.evaluate(() => window.settledThought.frames(5))
    const collapsed = await page.evaluate(() => window.settledThought.state)
    expect(collapsed.open).toBe(false)
    expect(collapsed.units).toBe(0)
    expect(await page.evaluate(() => performance.now()) - clicked).toBeLessThan(frameGapBoundMs)
    await page.evaluate(() => window.settledThought.frames(5))
    expect((await page.evaluate(() => window.settledThought.state)).units).toBe(0)
    await page.evaluate(() => window.settledThought.toggle())
    await page.waitForFunction(() => window.settledThought.state.exactText, undefined, { timeout: completionBoundMs, polling: 100 })
    expect((await page.evaluate(() => window.settledThought.state)).exactMarkup).toBe(true)
})

test('small expanded preview retains its open state when settled', async ({ page }) => {
    await page.goto('/settledThought.html')
    await page.evaluate(() => window.settledThought.mount('no-newline', true, 1000))
    await page.evaluate(() => window.settledThought.toggle())
    await page.waitForFunction(() => window.settledThought.state.previewOpen)
    await page.evaluate(() => window.settledThought.settle())
    await page.waitForFunction(() => window.settledThought.state.settled)
    const state = await page.evaluate(() => window.settledThought.state)
    expect(state.open).toBe(true)
    expect(state.exactText).toBe(true)
    expect(state.exactMarkup).toBe(true)
    expect(state.units).toBe(0)
})
