overrides:
  '@huggingface/transformers>onnxruntime-node': '-'
  '@huggingface/transformers>sharp': '-'
  'monaco-editor>dompurify': 3.4.15
  'rollup@>=4.0.0 <4.59.0': ^4.59.0
  'yaml@>=2.0.0 <2.8.3': ^2.8.3
minimumReleaseAgeExclude:
  - svelte@5.57.1
  - '@tauri-apps/plugin-updater@2.12.0'
