import { readFileSync } from 'node:fs'
import { afterEach, expect, it, vi } from 'vitest'
vi.mock('../stores.svelte', async () => ({ alertStore: (await import('../alertQueue')).createAlertQueue({ type: 'none', msg: '' }, { gapMs: 0 }) }))
import { alertStore } from '../stores.svelte'
import { get } from 'svelte/store'
import { modalNavigation, backNavigationLayer, handleRootBack } from './modalNavigation'

const rootBack = () => {
    const event = new Event('risunest-root-back', { cancelable: true })
    handleRootBack(event)
    return event.defaultPrevented
}

afterEach(() => {
    alertStore.set({ type: "none", msg: "" })
    vi.restoreAllMocks()
    history.replaceState(null, '')
    document.body.replaceChildren()
})
it('dismisses on Escape and restores focus to the opener', async () => {
    const opener = document.createElement('button'),
        modal = document.createElement('div')
    modal.innerHTML = '<button>Close</button>'
    document.body.append(opener, modal)
    opener.focus()
    const back = vi.spyOn(history, 'go').mockImplementation(() => {})
    const close = vi.fn()
    const action = modalNavigation(modal, { close })
    await Promise.resolve()
    expect(document.activeElement).toBe(modal.firstChild)
    window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }))
    expect(close).toHaveBeenCalledOnce()
    action.destroy()
    expect(document.activeElement).toBe(opener)
    await Promise.resolve()
    expect(back).toHaveBeenCalledWith(-1)
    back.mockRestore()
    history.replaceState(null, '')
    document.body.replaceChildren()
})
it('consumes a WebView/browser Back without going back a second time', () => {
    const back = vi.spyOn(history, 'go').mockImplementation(() => {})
    const close = vi.fn(),
        modal = document.createElement('div')
    const action = modalNavigation(modal, { close })
    history.replaceState(null, '')
    window.dispatchEvent(new PopStateEvent('popstate'))
    expect(close).toHaveBeenCalledOnce()
    action.destroy()
    expect(back).not.toHaveBeenCalled()
    back.mockRestore()
})

it('dismisses only the top nested dialog on Escape and preserves ancestors on Back', () => {
    const nodes = Array.from({ length: 3 }, () => document.createElement('div'))
    const closes = nodes.map(() => vi.fn())
    const states: unknown[] = []
    const actions = nodes.map((node, index) => {
        const action = modalNavigation(node, { close: closes[index] })
        states.push(history.state)
        return action
    })
    window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }))
    expect(closes[0]).not.toHaveBeenCalled()
    expect(closes[1]).not.toHaveBeenCalled()
    expect(closes[2]).toHaveBeenCalledOnce()

    history.replaceState(states[1], '')
    window.dispatchEvent(new PopStateEvent('popstate'))
    actions[2].destroy()
    expect(closes[0]).not.toHaveBeenCalled()
    expect(closes[1]).not.toHaveBeenCalled()

    history.replaceState(states[0], '')
    window.dispatchEvent(new PopStateEvent('popstate'))
    actions[1].destroy()
    expect(closes[0]).not.toHaveBeenCalled()
    expect(closes[1]).toHaveBeenCalledOnce()

    history.replaceState(null, '')
    window.dispatchEvent(new PopStateEvent('popstate'))
    actions[0].destroy()
    expect(closes[0]).toHaveBeenCalledOnce()
})

it('does not close a dialog for composition-owned Escape', () => {
    const close = vi.fn()
    const action = modalNavigation(document.createElement('div'), { close })
    for (const flags of [{ isComposing: true }, { keyCode: 229 }]) {
        const event = new KeyboardEvent('keydown', { key: 'Escape', cancelable: true, ...flags })
        window.dispatchEvent(event)
        expect(event.defaultPrevented).toBe(false)
    }
    expect(close).not.toHaveBeenCalled()
    history.replaceState(null, '')
    action.destroy()
})

it('coalesces nested teardown into one asynchronous traversal', async () => {
    const go = vi.spyOn(history, 'go').mockImplementation(() => {})
    const parent = modalNavigation(document.createElement('div'), { close: vi.fn() })
    const child = modalNavigation(document.createElement('div'), { close: vi.fn() })
    child.destroy()
    parent.destroy()
    await Promise.resolve()
    expect(go).toHaveBeenCalledOnce()
    expect(go).toHaveBeenCalledWith(-2)
})
it('cancels a sibling confirmation before closing a modal for Escape and Back', async () => {
    const close = vi.fn()
    const action = modalNavigation(document.createElement('div'), { close })
    const first = alertStore.open({ type: 'ask', msg: 'confirm' })
    window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }))
    expect(get(alertStore)).toEqual({ type: 'none', msg: '' })
    await expect(first).resolves.toBe('')
    expect(close).not.toHaveBeenCalled()
    const second = alertStore.open({ type: 'ask', msg: 'confirm again' })
    history.replaceState(null, '')
    window.dispatchEvent(new PopStateEvent('popstate'))
    expect(get(alertStore)).toEqual({ type: 'none', msg: '' })
    await expect(second).resolves.toBe('')
    expect(history.state.risunestModal).toHaveLength(1)
    expect(close).not.toHaveBeenCalled()
    history.replaceState(null, '')
    action.destroy()
})
it('keeps the modal open for Escape and Back pressed before the next queued confirmation shows', async () => {
    const close = vi.fn()
    const action = modalNavigation(document.createElement('div'), { close })
    const first = alertStore.open({ type: 'ask', msg: 'confirm' })
    const second = alertStore.open({ type: 'ask', msg: 'confirm again' })
    window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }))
    await expect(first).resolves.toBe('')
    window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }))
    history.replaceState(null, '')
    window.dispatchEvent(new PopStateEvent('popstate'))
    expect(close).not.toHaveBeenCalled()
    expect(history.state.risunestModal).toHaveLength(1)
    await new Promise((resolve) => setTimeout(resolve, 0))
    expect(get(alertStore)).toMatchObject({ type: 'ask', msg: 'confirm again' })
    window.dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape' }))
    await expect(second).resolves.toBe('')
    expect(close).not.toHaveBeenCalled()
    history.replaceState(null, '')
    action.destroy()
})
it('lets menu layers keep focus and opt out without a history entry', async () => {
    const opener = document.createElement('button'), menu = document.createElement('div')
    menu.innerHTML = '<button>Item</button>'
    document.body.append(opener, menu)
    opener.focus()
    const action = backNavigationLayer(menu, { close: vi.fn(), enabled: false })
    expect(history.state).toBeNull()
    action.update({ close: vi.fn(), enabled: true })
    await Promise.resolve()
    expect(document.activeElement).toBe(opener)
    history.replaceState(null, '')
    action.destroy()
})
it('leaves Escape to content that asks for it without closing the modal below', async () => {
    vi.spyOn(history, 'go').mockImplementation(() => {})
    const lower = document.createElement('div'), upper = document.createElement('div')
    upper.innerHTML = '<div data-editor><textarea></textarea></div><button>Close</button>'
    document.body.append(lower, upper)
    const editor = upper.querySelector('[data-editor]')!, field = upper.querySelector('textarea')!
    const closeLower = vi.fn(), closeUpper = vi.fn()
    const lowerAction = modalNavigation(lower, { close: closeLower })
    const upperAction = modalNavigation(upper, { close: closeUpper, leaveEscape: (event) => editor.contains(event.target as Node) })
    const escape = () => new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true })

    const left = escape()
    field.dispatchEvent(left)
    expect(left.defaultPrevented).toBe(false)
    expect(closeUpper).not.toHaveBeenCalled()
    expect(closeLower).not.toHaveBeenCalled()

    const confirmation = alertStore.open({ type: 'ask', msg: 'confirm' })
    const overAlert = escape()
    field.dispatchEvent(overAlert)
    expect(overAlert.defaultPrevented).toBe(true)
    expect(get(alertStore)).toEqual({ type: 'none', msg: '' })
    await expect(confirmation).resolves.toBe('')

    upper.querySelector('button')!.dispatchEvent(escape())
    expect(closeUpper).toHaveBeenCalledOnce()
    expect(closeLower).not.toHaveBeenCalled()
    upperAction.destroy()
    lowerAction.destroy()
})
it('cancels a confirmation shown outside every layer on the Android root Back', async () => {
    const confirmation = alertStore.open({ type: 'ask', msg: 'confirm' })
    expect(rootBack()).toBe(true)
    expect(get(alertStore)).toEqual({ type: 'none', msg: '' })
    await expect(confirmation).resolves.toBe('')
    expect(rootBack()).toBe(false)
})
it('holds the root Back while the next queued confirmation waits to show', async () => {
    const first = alertStore.open({ type: 'ask', msg: 'confirm' })
    const second = alertStore.open({ type: 'ask', msg: 'confirm again' })
    expect(rootBack()).toBe(true)
    await expect(first).resolves.toBe('')
    expect(rootBack()).toBe(true)
    await new Promise((resolve) => setTimeout(resolve, 0))
    expect(get(alertStore)).toMatchObject({ type: 'ask', msg: 'confirm again' })
    expect(rootBack()).toBe(true)
    await expect(second).resolves.toBe('')
})
it('leaves the root Back to the app for status alerts and RisuNest terms', async () => {
    alertStore.set({ type: 'wait', msg: 'loading' })
    expect(rootBack()).toBe(false)
    expect(get(alertStore)).toMatchObject({ type: 'wait' })
    alertStore.set({ type: 'none', msg: '' })
    const terms = alertStore.open({ type: 'tos', msg: 'tos' })
    expect(rootBack()).toBe(false)
    expect(get(alertStore)).toMatchObject({ type: 'tos' })
    alertStore.set({ type: 'none', msg: 'yes' })
    await expect(terms).resolves.toBe('yes')
})
it('closes the top layer through the page when the WebView skips its entry', async () => {
    const close = vi.fn()
    const sidebar = document.createElement('div')
    document.body.append(sidebar)
    const action = backNavigationLayer(sidebar, { close })
    expect(history.state?.risunestModal).toHaveLength(1)
    expect(rootBack()).toBe(true)
    expect(close).toHaveBeenCalledOnce()
    action.update({ close, enabled: false })
    await Promise.resolve()
    expect(rootBack()).toBe(false)
    action.destroy()
})
it('leaves the root Back to the app when only stale layer entries remain', async () => {
    const go = vi.spyOn(history, 'go').mockImplementation(() => {})
    const close = vi.fn()
    const action = backNavigationLayer(document.createElement('div'), { close })
    action.destroy()
    expect(history.state?.risunestModal).toHaveLength(1)
    expect(rootBack()).toBe(false)
    expect(close).not.toHaveBeenCalled()
    await Promise.resolve()
    expect(go).toHaveBeenCalledWith(-1)
})
it('cancels a dialog before the layer below it and keeps the terms over a layer', async () => {
    const back = vi.spyOn(history, 'back')
    const close = vi.fn()
    const action = backNavigationLayer(document.createElement('div'), { close })
    const confirmation = alertStore.open({ type: 'ask', msg: 'confirm' })
    expect(rootBack()).toBe(true)
    await expect(confirmation).resolves.toBe('')
    expect(back).not.toHaveBeenCalled()
    const terms = alertStore.open({ type: 'tos', msg: 'tos' })
    expect(rootBack()).toBe(false)
    expect(back).not.toHaveBeenCalled()
    expect(close).not.toHaveBeenCalled()
    alertStore.set({ type: 'none', msg: 'yes' })
    await expect(terms).resolves.toBe('yes')
    action.destroy()
})
it('receives the root Back event that MainActivity sends', () => {
    const activity = readFileSync('src-tauri/gen/android/app/src/main/java/io/github/rsyumi/risunest/MainActivity.kt', 'utf8')
    const app = readFileSync('src/App.svelte', 'utf8')
    expect(activity).toContain('private const val ROOT_BACK_EVENT = "risunest-root-back"')
    expect(app).toContain("window.addEventListener('risunest-root-back', handleRootBack)")
})
it('lets a Back-only layer close on Back while Escape stays with its content', async () => {
    const go = vi.spyOn(history, 'go').mockImplementation(() => {})
    const sidebar = document.createElement('div')
    sidebar.innerHTML = '<textarea></textarea>'
    document.body.append(sidebar)
    const close = vi.fn()
    const options = { enabled: false, close, leaveEscape: () => true }
    const action = backNavigationLayer(sidebar, options)
    expect(history.state).toBeNull()
    action.update({ ...options, enabled: true })
    const field = sidebar.querySelector('textarea')!
    const escape = new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true })
    field.dispatchEvent(escape)
    expect(escape.defaultPrevented).toBe(false)
    expect(close).not.toHaveBeenCalled()

    const confirmation = alertStore.open({ type: 'ask', msg: 'confirm' })
    const overAlert = new KeyboardEvent('keydown', { key: 'Escape', bubbles: true, cancelable: true })
    field.dispatchEvent(overAlert)
    expect(overAlert.defaultPrevented).toBe(true)
    expect(get(alertStore)).toEqual({ type: 'none', msg: '' })
    await expect(confirmation).resolves.toBe('')
    expect(close).not.toHaveBeenCalled()

    history.replaceState(null, '')
    window.dispatchEvent(new PopStateEvent('popstate'))
    expect(close).toHaveBeenCalledOnce()
    action.update({ ...options, enabled: false })
    await Promise.resolve()
    expect(go).not.toHaveBeenCalled()
    action.destroy()
})
