fn source_identity() -> (String, Vec<Value>) {
    let sources: &[(&str, &str, &[u8])] = &[
        (
            "crates/release-update/Cargo.toml",
            "normal-dependency",
            include_bytes!("../../../../crates/release-update/Cargo.toml"),
        ),
        (
            "crates/release-update/src/archive.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/release-update/src/archive.rs"),
        ),
        (
            "crates/release-update/src/contract.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/release-update/src/contract.rs"),
        ),
        (
            "crates/release-update/src/crypto.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/release-update/src/crypto.rs"),
        ),
        (
            "crates/release-update/src/lib.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/release-update/src/lib.rs"),
        ),
        (
            "crates/release-update/src/loader.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/release-update/src/loader.rs"),
        ),
        (
            "crates/small-object-store/Cargo.toml",
            "normal-dependency",
            include_bytes!("../../../../crates/small-object-store/Cargo.toml"),
        ),
        (
            "crates/small-object-store/src/lib.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/small-object-store/src/lib.rs"),
        ),
        (
            "crates/sync-connect/Cargo.toml",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-connect/Cargo.toml"),
        ),
        (
            "crates/sync-connect/src/directory.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-connect/src/directory.rs"),
        ),
        (
            "crates/sync-connect/src/lib.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-connect/src/lib.rs"),
        ),
        (
            "crates/sync-connect/src/media.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-connect/src/media.rs"),
        ),
        (
            "crates/sync-connect/src/media/tests.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-connect/src/media/tests.rs"),
        ),
        (
            "crates/sync-connect/src/registration.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-connect/src/registration.rs"),
        ),
        (
            "crates/sync-wire/Cargo.toml",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/Cargo.toml"),
        ),
        (
            "crates/sync-wire/src/canonical.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/canonical.rs"),
        ),
        (
            "crates/sync-wire/src/changes.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/changes.rs"),
        ),
        (
            "crates/sync-wire/src/delta.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/delta.rs"),
        ),
        (
            "crates/sync-wire/src/descriptor.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/descriptor.rs"),
        ),
        (
            "crates/sync-wire/src/head.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/head.rs"),
        ),
        (
            "crates/sync-wire/src/lib.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/lib.rs"),
        ),
        (
            "crates/sync-wire/src/lww.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/lww.rs"),
        ),
        (
            "crates/sync-wire/src/order.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/order.rs"),
        ),
        (
            "crates/sync-wire/src/payload_value.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/payload_value.rs"),
        ),
        (
            "crates/sync-wire/src/payload.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/payload.rs"),
        ),
        (
            "crates/sync-wire/src/stamp.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/stamp.rs"),
        ),
        (
            "crates/sync-wire/src/stream_delta.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/stream_delta.rs"),
        ),
        (
            "crates/sync-wire/src/transfer.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/transfer.rs"),
        ),
        (
            "crates/sync-wire/src/unit.rs",
            "normal-dependency",
            include_bytes!("../../../../crates/sync-wire/src/unit.rs"),
        ),
        (
            "server/sync/Cargo.lock",
            "server",
            include_bytes!("../../../../server/sync/Cargo.lock"),
        ),
        (
            "server/sync/Cargo.toml",
            "server",
            include_bytes!("../../../../server/sync/Cargo.toml"),
        ),
        (
            "server/sync/src/config.rs",
            "server",
            include_bytes!("../../../../server/sync/src/config.rs"),
        ),
        (
            "server/sync/src/connection.rs",
            "server",
            include_bytes!("../../../../server/sync/src/connection.rs"),
        ),
        (
            "server/sync/src/http/lww.rs",
            "server",
            include_bytes!("../../../../server/sync/src/http/lww.rs"),
        ),
        (
            "server/sync/src/http/mod.rs",
            "server",
            include_bytes!("../../../../server/sync/src/http/mod.rs"),
        ),
        (
            "server/sync/src/identity.rs",
            "server",
            include_bytes!("../../../../server/sync/src/identity.rs"),
        ),
        (
            "server/sync/src/lib.rs",
            "server",
            include_bytes!("../../../../server/sync/src/lib.rs"),
        ),
        (
            "server/sync/src/main.rs",
            "server",
            include_bytes!("../../../../server/sync/src/main.rs"),
        ),
        (
            "server/sync/src/management_tests.rs",
            "server",
            include_bytes!("../../../../server/sync/src/management_tests.rs"),
        ),
        (
            "server/sync/src/management/discovery.rs",
            "server",
            include_bytes!("../../../../server/sync/src/management/discovery.rs"),
        ),
        (
            "server/sync/src/management/mod.rs",
            "server",
            include_bytes!("../../../../server/sync/src/management/mod.rs"),
        ),
        (
            "server/sync/src/management/storage.rs",
            "server",
            include_bytes!("../../../../server/sync/src/management/storage.rs"),
        ),
        (
            "server/sync/src/publication.rs",
            "server",
            include_bytes!("../../../../server/sync/src/publication.rs"),
        ),
        (
            "server/sync/src/runtime.rs",
            "server",
            include_bytes!("../../../../server/sync/src/runtime.rs"),
        ),
        (
            "server/sync/src/source_observer_harness.rs",
            "server",
            include_bytes!("../../../../server/sync/src/source_observer_harness.rs"),
        ),
        (
            "server/sync/src/source_observer/mod.rs",
            "server",
            include_bytes!("../../../../server/sync/src/source_observer/mod.rs"),
        ),
        (
            "server/sync/src/source_observer/read_barrier.rs",
            "server",
            include_bytes!("../../../../server/sync/src/source_observer/read_barrier.rs"),
        ),
        (
            "server/sync/src/source_observer/shared_wire.rs",
            "server",
            include_bytes!("../../../../server/sync/src/source_observer/shared_wire.rs"),
        ),
        (
            "server/sync/src/source_observer/source_identity.rs",
            "server",
            include_bytes!("../../../../server/sync/src/source_observer/source_identity.rs"),
        ),
        (
            "server/sync/src/source_observer/tests.rs",
            "server",
            include_bytes!("../../../../server/sync/src/source_observer/tests.rs"),
        ),
        (
            "server/sync/src/store/backup.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/backup.rs"),
        ),
        (
            "server/sync/src/store/connection.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/connection.rs"),
        ),
        (
            "server/sync/src/store/descriptors_index.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/descriptors_index.rs"),
        ),
        (
            "server/sync/src/store/descriptors.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/descriptors.rs"),
        ),
        (
            "server/sync/src/store/lww_tests.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/lww_tests.rs"),
        ),
        (
            "server/sync/src/store/lww.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/lww.rs"),
        ),
        (
            "server/sync/src/store/maintenance.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/maintenance.rs"),
        ),
        (
            "server/sync/src/store/management.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/management.rs"),
        ),
        (
            "server/sync/src/store/media.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/media.rs"),
        ),
        (
            "server/sync/src/store/media/tests.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/media/tests.rs"),
        ),
        (
            "server/sync/src/store/mod.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/mod.rs"),
        ),
        (
            "server/sync/src/store/objects.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/objects.rs"),
        ),
        (
            "server/sync/src/store/registration_claims.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/registration_claims.rs"),
        ),
        (
            "server/sync/src/store/retention.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/retention.rs"),
        ),
        (
            "server/sync/src/store/retention/tests.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/retention/tests.rs"),
        ),
        (
            "server/sync/src/store/schema.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/schema.rs"),
        ),
        (
            "server/sync/src/store/stream_transfers.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/stream_transfers.rs"),
        ),
        (
            "server/sync/src/store/transfers.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/transfers.rs"),
        ),
        (
            "server/sync/src/store/upload_jobs.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/upload_jobs.rs"),
        ),
        (
            "server/sync/src/store/uploads.rs",
            "server",
            include_bytes!("../../../../server/sync/src/store/uploads.rs"),
        ),
        (
            "server/sync/src/tunnel_job.rs",
            "server",
            include_bytes!("../../../../server/sync/src/tunnel_job.rs"),
        ),
        (
            "server/sync/src/tunnel.rs",
            "server",
            include_bytes!("../../../../server/sync/src/tunnel.rs"),
        ),
        (
            "server/sync/src/update.rs",
            "server",
            include_bytes!("../../../../server/sync/src/update.rs"),
        ),
        (
            "server/sync/src/workload.rs",
            "server",
            include_bytes!("../../../../server/sync/src/workload.rs"),
        ),
        (
            "crates/small-object-store/src/lib.rs",
            "source-linked",
            include_bytes!("../../../../crates/small-object-store/src/lib.rs"),
        ),
        (
            "crates/sync-wire/src/delta.rs",
            "source-linked",
            include_bytes!("../../../../crates/sync-wire/src/delta.rs"),
        ),
        (
            "crates/sync-wire/src/stream_delta.rs",
            "source-linked",
            include_bytes!("../../../../crates/sync-wire/src/stream_delta.rs"),
        ),
        (
            "crates/sync-wire/src/transfer.rs",
            "source-linked",
            include_bytes!("../../../../crates/sync-wire/src/transfer.rs"),
        ),
    ];
    let mut fingerprint = Sha256::new();
    let mut closure = Vec::new();
    for (path, role, bytes) in sources {
        for value in [path.as_bytes(), role.as_bytes(), *bytes] {
            fingerprint.update((value.len() as u64).to_be_bytes());
            fingerprint.update(value);
        }
        closure.push(json!({"path":path,"role":role,"sha256":hex::encode(Sha256::digest(bytes))}));
    }
    (hex::encode(fingerprint.finalize()), closure)
}
