[package]
name = "risunest-sync-gui"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
name = "risunest_sync_gui_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[features]
custom-protocol = ["tauri/custom-protocol"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = ["tray-icon", "macos-private-api"] }
risunest-sync-manager = { path = "../.." }
risunest-sync-server = { path = "../../../sync" }
risunest-sync-connect = { path = "../../../../crates/sync-connect" }
serde_json = "1"
tokio = { version = "1", features = ["time"] }
qrcode = { version = "0.14", default-features = false }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.3", features = ["Win32_Foundation", "Win32_Graphics_Gdi", "Win32_System_LibraryLoader", "Win32_UI_HiDpi", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_WindowsAndMessaging"] }
